project_id = "baujoowgqeyraqnukkmw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://baujoowgqeyraqnukkmw.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

# Security configurations for auth
[auth.security]
captcha_enabled = true
refresh_token_rotation_enabled = true
password_min_length = 8
password_require_uppercase = true
password_require_lowercase = true
password_require_numbers = true
password_require_special = true
max_password_length = 128

# Enhanced security settings
[auth.external]
enable_leaked_password_protection = true

[auth.sessions]
timebox = 3600
inactivity_timeout = 1800

# Enable leaked password protection (security fix)
[auth.password_security]
password_min_length = 8
password_require_uppercase = true
password_require_lowercase = true 
password_require_numbers = true
password_require_special = true
max_password_length = 128
enable_leaked_password_protection = true

# Secure endpoints - require authentication or HMAC
[functions.log-visit]
verify_jwt = false

[functions.blog-theme-normalizer]
verify_jwt = true

[functions.security-audit]
verify_jwt = true

[functions.verify-ai-token]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = true

[functions.secure-contact]
verify_jwt = false

# Public endpoints (no JWT required)  
[functions.sitemap]
verify_jwt = false

[functions.blog-sitemap]
verify_jwt = false

[functions.news-sitemap]
verify_jwt = false

[functions.blog-rss]
verify_jwt = false

[functions.update-sitemaps]
verify_jwt = false

[functions.redirect-handler]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = true

[functions.advanced-article-generator]
verify_jwt = true

# Secure admin functions require JWT
[functions.admin-blog-create-ai]
verify_jwt = true

[functions.admin-blog-drafts]
verify_jwt = true

[functions.admin-blog-list]
verify_jwt = true

[functions.admin-categories]
verify_jwt = true

[functions.analytics-display]
verify_jwt = true

[functions.image-optimizer]
verify_jwt = true

[functions.indexnow-submitter]
verify_jwt = true

[functions.jsonld-optimizer]
verify_jwt = true

[functions.internal-linker]
verify_jwt = true

[functions.slug-normalizer]
verify_jwt = true

[functions.override-orchestrator]
verify_jwt = true

[functions.final-audit]
verify_jwt = true

[functions.content-fixer]
verify_jwt = true

[functions.blog-content-fixer]
verify_jwt = true

[functions.blog-theme-normalizer]
verify_jwt = true

[functions.restore-backups]
verify_jwt = true

[functions.runware-image]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.gemini-image]
verify_jwt = true

[functions.gemini-provider]
verify_jwt = true

[functions.get-users]
verify_jwt = true

# Public analytics endpoint
[functions.log-visit-public]
verify_jwt = false

# All other functions require JWT by default