project_id = "baujoowgqeyraqnukkmw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://baujoowgqeyraqnukkmw.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

# Public endpoints (no JWT required)
[functions.ai-auth]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.blog-sitemap]
verify_jwt = false

[functions.news-sitemap]
verify_jwt = false

[functions.blog-rss]
verify_jwt = false

[functions.update-sitemaps]
verify_jwt = false

[functions.redirect-handler]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.verify-ai-token]
verify_jwt = false

[functions.security-audit]
verify_jwt = false

# All other functions require JWT by default (no override here)
